kind: Secret
apiVersion: v1
metadata:
  name: streamlit-secret
  namespace: st-report
  labels:
    app: st-report
data:
  secrets.toml: |
    [passwords]
    # Follow the rule: username = "password"
    admin = "xxx"
type: Opaque
