apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: registryNamespace
      description: the ibmcloud registry namespace
      default: sr-report
    - name: registryRegion
      description: the ibmcloud registry region
      default: global
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
      default: k8s-lite
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: eu-de
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: sr-report
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-pvc
            emptyDir: {}
        params:
          - name: repository
            value: $(params.repository)
          - name: revision
            value: $(params.revision)
          - name: apikey
            value: $(params.apikey)
          - name: registryNamespace
            value: $(params.registryNamespace)
          - name: registryRegion
            value: $(params.registryRegion)
          - name: cluster
            value: $(params.cluster)
          - name: clusterRegion
            value: $(params.clusterRegion)
          - name: clusterNamespace
            value: $(params.clusterNamespace)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.pull_request.head.sha)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - interceptors:
        - name: "only PRs"
          ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      binding:
        name: binding
      template:
        name: template
